# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joven < Formula
  desc ""
  homepage "https://github.com/netvolart/joven"
  version "0.0.2"

  on_macos do
    url "https://github.com/netvolart/joven/releases/download/v0.0.2/joven_0.0.2_darwin_all.tar.gz"
    sha256 "e13f55d941b139612d6b3c62d41e2448ba1106b46b095cf68b6f1d305814790c"

    def install
      bin.install "joven"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/netvolart/joven/releases/download/v0.0.2/joven_0.0.2_linux_amd64.tar.gz"
      sha256 "4f2d70065bba84759b1b63154cacc9078634ca1e8b9ace857696bf5e72771a69"

      def install
        bin.install "joven"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netvolart/joven/releases/download/v0.0.2/joven_0.0.2_linux_arm64.tar.gz"
      sha256 "e4b14a5a81c8cb122033ecac1ce9a59a9b923a964ae05bca8caa92ae452b144e"

      def install
        bin.install "joven"
      end
    end
  end
end
