# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joven < Formula
  desc ""
  homepage "https://github.com/netvolart/joven"
  version "0.0.1"

  on_macos do
    url "https://github.com/netvolart/joven/releases/download/v0.0.1/joven_0.0.1_darwin_all.tar.gz"
    sha256 "75b8696ea25ac81eb75dd598c8f0a48561fb4180923a55a2dbfccabccc0ddb3b"

    def install
      bin.install "joven"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/netvolart/joven/releases/download/v0.0.1/joven_0.0.1_linux_amd64.tar.gz"
      sha256 "0f7ca36b97884aaf03e37866a6b28b808fd798fd3d97d8dd3e5a087f50159f80"

      def install
        bin.install "joven"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netvolart/joven/releases/download/v0.0.1/joven_0.0.1_linux_arm64.tar.gz"
      sha256 "67a3dae1da9fc66aae3c512cd24d6c0dfb7f890298d9d233945856ff9d76946e"

      def install
        bin.install "joven"
      end
    end
  end
end
