# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joven < Formula
  desc ""
  homepage "https://github.com/netvolart/joven"
  version "0.0.3"

  on_macos do
    url "https://github.com/netvolart/joven/releases/download/v0.0.3/joven_0.0.3_darwin_all.tar.gz"
    sha256 "ebdb9dc95e0250fa75d60e43cc6971dfdf4de1c486f14369328c5b8445e2898f"

    def install
      bin.install "joven"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/netvolart/joven/releases/download/v0.0.3/joven_0.0.3_linux_amd64.tar.gz"
      sha256 "1201e80aa3ff3a0bf1de42660dddf7437c5377783121dab6953738d5ac68aa28"

      def install
        bin.install "joven"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netvolart/joven/releases/download/v0.0.3/joven_0.0.3_linux_arm64.tar.gz"
      sha256 "05e6d61d60a65b0e9cced1c66ab1b668509a9fe945bd8c1b9569940110d1c921"

      def install
        bin.install "joven"
      end
    end
  end
end
